server:
  port: 8111

spring:
  application:
    name: order-system
  datasource:
    resource:
      pool-name: hikari-resource-pool
      jdbc-url: jdbc:mysql://localhost:3306/order_resource
      username: root
      password: 123456
      driver-class: com.mysql.cj.jdbc.Driver
    form:
      pool-name: hikari-form-pool
      jdbc-url: jdbc:mysql://localhost:3306/order_form
      username: root
      password: 123456
      driver-class: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 100000
      connection-test-query: select now()
      keepalive-time: 300000
      idle-timeout: 60000
      auto-commit: true
  jpa:
    show-sql: true
    database: mysql
    open-in-view: true
  jackson:
    time-zone: GMT+8

  redis:
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: 50000
    host: localhost
    port: 6379


order-system:
  white-list-url:
    - /login
