server:
  port: 8111

spring:
  application:
    name: order-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    resource:
      type: com.alibaba.druid.pool.DruidDataSource
      name: druid-resource-pool
      url: jdbc:mysql://localhost:3306/order_resource
      username: root
      password: 123456
      driver-class: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      max-wait: 60000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      pool-prepared-statements: false
      validation-query: select now()
      filters: stat, wall
    form:
      type: com.alibaba.druid.pool.DruidDataSource
      name: druid-form-pool
      url: jdbc:mysql://localhost:3306/order_form
      username: root
      password: 123456
      driver-class: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      max-wait: 60000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      pool-prepared-statements: false
      validation-query: select now()
      filters: stat, wall
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  jpa:
    show-sql: true
    database: mysql
    open-in-view: true
  jackson:
    time-zone: GMT+8

  redis:
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: 50000
    host: localhost
    port: 6379


order-system:
  white-list-url:
    - /login
    - /druid
    - /actuator
    - /favicon.ico
